2025-05-13 02:58:14,714: INFO: Accessed /send-email-page
2025-05-13 03:03:25,933: INFO: Accessed /send-email-page
2025-05-15 21:16:32,246: INFO: Accessed /send-email-page
2025-05-17 13:26:22,785: ERROR: OSError: write error
2025-05-17 13:50:05,205: INFO: Accessed /send-email-page
2025-05-20 14:40:33,099: ERROR: OSError: write error
2025-05-23 14:11:01,025: ERROR: OSError: write error
2025-05-26 01:32:19,330: ERROR: Error running WSGI application
2025-05-26 01:32:19,342: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: resume_submit2ai
2025-05-26 01:32:19,343: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-05-26 01:32:19,343: ERROR:     from app import app as application
2025-05-26 01:32:19,344: ERROR: 
2025-05-26 01:32:19,344: ERROR:   File "/home/ocottrell/unemployment/app.py", line 82, in <module>
2025-05-26 01:32:19,345: ERROR:     def resume_submit2ai():
2025-05-26 01:32:19,346: ERROR: 
2025-05-26 01:32:19,347: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-05-26 01:32:19,347: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-05-26 01:32:19,347: ERROR: 
2025-05-26 01:32:19,348: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-05-26 01:32:19,348: ERROR:     return f(self, *args, **kwargs)
2025-05-26 01:32:19,348: ERROR: 
2025-05-26 01:32:19,348: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-05-26 01:32:19,348: ERROR:     raise AssertionError(
2025-05-26 01:32:19,348: ERROR: ***************************************************
2025-05-26 01:32:19,348: ERROR: If you're seeing an import error and don't know why,
2025-05-26 01:32:19,349: ERROR: we have a dedicated help page to help you debug: 
2025-05-26 01:32:19,349: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-05-26 01:32:19,349: ERROR: ***************************************************
2025-05-26 01:32:26,978: ERROR: Error running WSGI application
2025-05-26 01:32:26,984: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: resume_submit2ai
2025-05-26 01:32:26,984: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-05-26 01:32:26,985: ERROR:     from app import app as application
2025-05-26 01:32:26,985: ERROR: 
2025-05-26 01:32:26,988: ERROR:   File "/home/ocottrell/unemployment/app.py", line 82, in <module>
2025-05-26 01:32:26,988: ERROR:     def resume_submit2ai():
2025-05-26 01:32:26,988: ERROR: 
2025-05-26 01:32:26,988: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-05-26 01:32:26,989: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-05-26 01:32:26,989: ERROR: 
2025-05-26 01:32:26,989: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-05-26 01:32:26,989: ERROR:     return f(self, *args, **kwargs)
2025-05-26 01:32:26,990: ERROR: 
2025-05-26 01:32:26,990: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-05-26 01:32:26,990: ERROR:     raise AssertionError(
2025-05-26 01:32:26,992: ERROR: ***************************************************
2025-05-26 01:32:26,992: ERROR: If you're seeing an import error and don't know why,
2025-05-26 01:32:26,992: ERROR: we have a dedicated help page to help you debug: 
2025-05-26 01:32:26,993: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-05-26 01:32:26,993: ERROR: ***************************************************
2025-05-26 01:33:20,550: ERROR: Error running WSGI application
2025-05-26 01:33:20,556: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: resume_submit2ai
2025-05-26 01:33:20,556: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-05-26 01:33:20,556: ERROR:     from app import app as application
2025-05-26 01:33:20,556: ERROR: 
2025-05-26 01:33:20,557: ERROR:   File "/home/ocottrell/unemployment/app.py", line 82, in <module>
2025-05-26 01:33:20,557: ERROR:     def resume_submit2ai():
2025-05-26 01:33:20,557: ERROR: 
2025-05-26 01:33:20,557: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-05-26 01:33:20,557: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-05-26 01:33:20,557: ERROR: 
2025-05-26 01:33:20,558: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-05-26 01:33:20,558: ERROR:     return f(self, *args, **kwargs)
2025-05-26 01:33:20,558: ERROR: 
2025-05-26 01:33:20,559: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-05-26 01:33:20,559: ERROR:     raise AssertionError(
2025-05-26 01:33:20,559: ERROR: ***************************************************
2025-05-26 01:33:20,559: ERROR: If you're seeing an import error and don't know why,
2025-05-26 01:33:20,560: ERROR: we have a dedicated help page to help you debug: 
2025-05-26 01:33:20,560: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-05-26 01:33:20,560: ERROR: ***************************************************
2025-05-26 19:11:41,856: INFO: Accessed /send-email-page
2025-05-26 19:12:52,334: INFO: Accessed /send-email-page
2025-05-26 19:22:53,470: INFO: Accessed /send-email-page
2025-05-26 20:02:23,605: INFO: Accessed /send-email-page
2025-05-26 20:03:01,620: INFO: Received POST request to /send-email
2025-05-26 20:03:01,624: ERROR: Email list file not found: /home/ocottrell/unemployment/static/stdavid_emails.txt
2025-05-26 20:17:57,287: INFO: Accessed /send-email-page
2025-05-26 20:18:13,293: INFO: Accessed /send-email-page
2025-05-26 20:19:13,221: INFO: Accessed /send-email-page
2025-05-26 20:19:56,862: INFO: Accessed /send-email-page
2025-05-26 20:20:16,674: INFO: Received POST request to /send-email
2025-05-26 20:20:16,819: INFO: SMTP login successful
2025-05-26 20:20:18,415: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-05-26 20:41:17,644: INFO: Accessed /send-email-page
2025-05-26 21:08:19,108: INFO: Received POST request to /send-email
2025-05-26 21:08:19,345: INFO: SMTP login successful
2025-05-26 21:08:20,080: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-05-26 21:36:45,903: INFO: Accessed /send-email-page
2025-05-26 21:39:03,897: INFO: Accessed /send-email-page
2025-05-26 21:48:32,491: INFO: Accessed /send-email-page
2025-05-26 21:50:13,482: INFO: Accessed /send-email-page
2025-05-26 21:53:01,673: INFO: Accessed /send-email-page
2025-05-27 02:52:20,131: ERROR: Exception on /custom-cover-help [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 119, in custom_resume_help
    return render_template('Cover-Custom-Help.html', host=request.host)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Cover-Custom-Help.html
2025-05-27 03:26:51,161: INFO: Accessed /send-email-page
2025-05-27 03:32:53,250: INFO: Accessed /send-email-page
2025-05-28 00:49:20,398: ERROR: OSError: write error
2025-06-01 19:49:52,565: INFO: Accessed /send-email-page
2025-06-02 00:22:36,936: INFO: Accessed /send-email-page
2025-06-02 00:58:47,650: ERROR: OSError: write error
2025-06-03 11:45:03,255: ERROR: OSError: write error
2025-06-04 00:28:45,662: ERROR: OSError: write error
2025-06-05 03:08:08,268: ERROR: Exception on /ministers-help [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 75, in ministers_help
    return render_template('Ministers-Help.html', host=request.host)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Ministers-Help.html
2025-06-12 21:43:47,177: ERROR: OSError: write error
2025-06-14 23:52:37,784: INFO: Accessed /send-email-page
2025-06-21 19:55:36,762: ERROR: OSError: write error
2025-06-23 18:23:01,144: ERROR: OSError: write error
2025-06-24 23:26:40,221: ERROR: OSError: write error
2025-06-27 21:21:37,757: ERROR: OSError: write error
2025-06-30 17:50:46,168: INFO: Accessed /send-email-page
2025-06-30 19:52:05,119: INFO: Accessed /send-email-page
2025-07-01 18:38:19,701: ERROR: OSError: write error
2025-07-02 18:28:46,674: ERROR: OSError: write error
2025-07-03 07:47:26,084: ERROR: OSError: write error
2025-07-05 02:14:19,761: ERROR: OSError: write error
2025-07-06 20:56:31,382: INFO: Accessed /send-email-page
2025-07-07 17:35:13,941: ERROR: OSError: write error
2025-07-07 17:44:28,716: ERROR: OSError: write error
2025-07-07 17:51:41,755: ERROR: OSError: write error
2025-07-07 17:54:49,357: INFO: Accessed /send-email-page
2025-07-07 17:59:08,799: INFO: Accessed /send-email-page
2025-07-07 18:18:45,587: INFO: Accessed /send-email-page
2025-07-08 15:06:26,739: ERROR: OSError: write error
2025-07-11 10:49:15,902: ERROR: OSError: write error
2025-07-12 10:15:26,808: ERROR: OSError: write error
2025-07-13 08:08:31,183: ERROR: OSError: write error
2025-07-14 13:38:27,984: ERROR: OSError: write error
2025-07-15 07:51:20,277: ERROR: OSError: write error
2025-07-18 04:20:53,966: INFO: Accessed /send-email-page
2025-07-18 15:37:28,609: INFO: Accessed /send-email-page
2025-07-18 16:38:10,190: ERROR: OSError: write error
2025-07-19 06:23:29,141: INFO: Accessed /send-email-page
2025-07-19 06:57:48,046: INFO: Accessed /send-email-page
2025-07-19 07:55:03,904: INFO: Accessed /send-email-page
2025-07-20 08:27:48,959: INFO: Accessed /send-email-page
2025-07-20 14:08:00,331: INFO: Accessed /send-email-page
2025-07-20 15:07:58,667: INFO: Accessed /send-email-page
2025-07-21 04:27:25,883: ERROR: OSError: write error
2025-07-22 03:23:05,161: INFO: Accessed /send-email-page
2025-07-22 09:20:38,427: INFO: Accessed /send-email-page
2025-07-22 10:45:07,528: INFO: Accessed /send-email-page
2025-07-22 16:22:14,031: ERROR: OSError: write error
2025-07-22 21:21:18,163: INFO: Accessed /send-email-page
2025-07-23 16:12:14,322: ERROR: OSError: write error
2025-07-23 22:07:35,621: INFO: Accessed /send-email-page
2025-07-24 14:02:27,917: INFO: Accessed /send-email-page
2025-07-25 10:50:08,933: ERROR: OSError: write error
2025-07-27 00:34:00,562: ERROR: OSError: write error
2025-07-28 10:24:46,365: ERROR: OSError: write error
2025-07-28 10:30:38,378: INFO: Accessed /send-email-page
2025-07-28 10:31:08,205: INFO: Accessed /send-email-page
2025-07-28 10:31:12,479: INFO: Accessed /send-email-page
2025-07-28 10:31:12,789: INFO: Accessed /send-email-page
2025-07-28 10:31:12,793: INFO: Accessed /send-email-page
2025-07-28 10:31:38,578: INFO: Accessed /send-email-page
2025-07-28 10:39:07,734: INFO: Accessed /send-email-page
2025-07-28 10:40:26,287: INFO: Received POST request to /send-email
2025-07-28 10:40:26,516: INFO: SMTP login successful
2025-07-28 10:40:27,469: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 10:40:34,150: INFO: Received POST request to /send-email
2025-07-28 10:40:34,355: INFO: SMTP login successful
2025-07-28 10:40:34,997: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 12:31:05,414: ERROR: Exception on /resume-draft [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 82, in resume_draft
    return render_template('Resume-Draft.html', host=request.host)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ocottrell/unemployment/templates/Resume-Draft.html", line 673, in template
    "{{{\n"
jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 25745
2025-07-28 17:15:36,539: INFO: Received POST request to /send-email
2025-07-28 17:15:36,762: INFO: SMTP login successful
2025-07-28 17:15:38,270: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:16:12,819: INFO: Received POST request to /send-email
2025-07-28 17:16:13,073: INFO: SMTP login successful
2025-07-28 17:16:13,800: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:22:06,937: INFO: Received POST request to /send-email
2025-07-28 17:22:07,170: INFO: SMTP login successful
2025-07-28 17:22:08,277: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:25:47,576: INFO: Received POST request to /send-email
2025-07-28 17:25:47,757: INFO: SMTP login successful
2025-07-28 17:25:48,572: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:36:58,386: INFO: Received POST request to /send-email
2025-07-28 17:36:58,694: INFO: SMTP login successful
2025-07-28 17:36:59,531: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:37:08,732: INFO: Received POST request to /send-email
2025-07-28 17:37:08,905: INFO: SMTP login successful
2025-07-28 17:37:09,954: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:39:09,466: INFO: Received POST request to /send-email
2025-07-28 17:39:09,657: INFO: SMTP login successful
2025-07-28 17:39:10,493: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:41:33,821: INFO: Received POST request to /send-email
2025-07-28 17:41:34,061: INFO: SMTP login successful
2025-07-28 17:41:35,161: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:42:02,879: INFO: Received POST request to /send-email
2025-07-28 17:42:03,103: INFO: SMTP login successful
2025-07-28 17:42:03,901: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:42:13,227: INFO: Received POST request to /send-email
2025-07-28 17:42:13,400: INFO: SMTP login successful
2025-07-28 17:42:14,273: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:42:14,520: INFO: Received POST request to /send-email
2025-07-28 17:42:14,755: INFO: SMTP login successful
2025-07-28 17:42:15,992: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:44:03,157: INFO: Received POST request to /send-email
2025-07-28 17:44:03,355: INFO: SMTP login successful
2025-07-28 17:44:04,400: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:44:11,146: INFO: Received POST request to /send-email
2025-07-28 17:44:11,357: INFO: SMTP login successful
2025-07-28 17:44:12,090: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 17:48:19,907: INFO: Received POST request to /send-email
2025-07-28 17:48:20,167: INFO: SMTP login successful
2025-07-28 17:48:20,939: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 20:34:38,537: INFO: Accessed /send-email-page
2025-07-28 20:34:44,962: INFO: Accessed /send-email-page
2025-07-28 20:35:10,991: INFO: Received POST request to /send-email
2025-07-28 20:35:11,257: INFO: SMTP login successful
2025-07-28 20:35:12,088: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 20:35:14,565: INFO: Received POST request to /send-email
2025-07-28 20:35:14,725: INFO: SMTP login successful
2025-07-28 20:35:15,265: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 20:35:22,182: INFO: Received POST request to /send-email
2025-07-28 20:35:22,356: INFO: SMTP login successful
2025-07-28 20:35:22,979: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-28 20:38:26,322: INFO: Received POST request to /send-email
2025-07-28 20:38:26,476: INFO: SMTP login successful
2025-07-28 20:38:27,036: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 00:59:32,704: INFO: Received POST request to /send-email
2025-07-29 00:59:33,058: INFO: SMTP login successful
2025-07-29 00:59:34,255: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 02:13:36,484: INFO: Received POST request to /send-email
2025-07-29 02:13:36,677: INFO: SMTP login successful
2025-07-29 02:13:38,441: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 04:47:10,544: INFO: Received POST request to /send-email
2025-07-29 04:47:10,815: INFO: SMTP login successful
2025-07-29 04:47:12,135: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 04:47:12,144: INFO: Received POST request to /send-email
2025-07-29 04:47:12,540: INFO: SMTP login successful
2025-07-29 04:47:13,318: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 04:52:14,301: INFO: Received POST request to /send-email
2025-07-29 04:52:14,523: INFO: SMTP login successful
2025-07-29 04:52:15,064: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 04:52:15,485: INFO: Received POST request to /send-email
2025-07-29 04:52:15,725: INFO: SMTP login successful
2025-07-29 04:52:16,407: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 04:57:22,855: INFO:  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2025-07-29 04:57:22,859: INFO:  * Restarting with stat
2025-07-29 05:01:16,510: INFO: Received POST request to /send-email
2025-07-29 05:01:16,827: INFO: SMTP login successful
2025-07-29 05:01:17,932: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 05:01:17,952: INFO: Received POST request to /send-email
2025-07-29 05:01:18,157: INFO: SMTP login successful
2025-07-29 05:01:19,436: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 05:25:31,147: INFO: Received POST request to /send-email
2025-07-29 05:25:31,473: INFO: SMTP login successful
2025-07-29 05:25:32,467: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 05:40:31,225: INFO: Received POST request to /send-email
2025-07-29 05:40:31,488: INFO: SMTP login successful
2025-07-29 05:40:32,551: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 05:40:40,142: INFO: Received POST request to /send-email
2025-07-29 05:40:40,369: INFO: SMTP login successful
2025-07-29 05:40:41,181: INFO: Received POST request to /send-email
2025-07-29 05:40:41,350: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 05:40:41,421: INFO: SMTP login successful
2025-07-29 05:40:42,452: INFO: Email sent to ocottrell@gmail.com
thebooksoft@gmail.com
2025-07-29 09:14:17,374: ERROR: Error running WSGI application
2025-07-29 09:14:17,383: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:14:17,384: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:14:17,384: ERROR:     from app import app as application
2025-07-29 09:14:17,384: ERROR: 
2025-07-29 09:14:17,384: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:14:17,384: ERROR:     def feed_back():
2025-07-29 09:14:17,385: ERROR: 
2025-07-29 09:14:17,385: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:14:17,385: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:14:17,385: ERROR: 
2025-07-29 09:14:17,385: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:14:17,385: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:14:17,385: ERROR: 
2025-07-29 09:14:17,386: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:14:17,386: ERROR:     raise AssertionError(
2025-07-29 09:14:17,386: ERROR: ***************************************************
2025-07-29 09:14:17,386: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:14:17,386: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:14:17,387: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:14:17,387: ERROR: ***************************************************
2025-07-29 09:14:28,438: ERROR: Error running WSGI application
2025-07-29 09:14:28,443: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:14:28,443: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:14:28,444: ERROR:     from app import app as application
2025-07-29 09:14:28,444: ERROR: 
2025-07-29 09:14:28,444: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:14:28,444: ERROR:     def feed_back():
2025-07-29 09:14:28,444: ERROR: 
2025-07-29 09:14:28,444: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:14:28,444: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:14:28,445: ERROR: 
2025-07-29 09:14:28,445: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:14:28,445: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:14:28,445: ERROR: 
2025-07-29 09:14:28,445: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:14:28,445: ERROR:     raise AssertionError(
2025-07-29 09:14:28,445: ERROR: ***************************************************
2025-07-29 09:14:28,446: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:14:28,446: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:14:28,446: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:14:28,446: ERROR: ***************************************************
2025-07-29 09:14:40,263: ERROR: Error running WSGI application
2025-07-29 09:14:40,264: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:14:40,264: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:14:40,265: ERROR:     from app import app as application
2025-07-29 09:14:40,265: ERROR: 
2025-07-29 09:14:40,265: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:14:40,265: ERROR:     def feed_back():
2025-07-29 09:14:40,265: ERROR: 
2025-07-29 09:14:40,266: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:14:40,266: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:14:40,266: ERROR: 
2025-07-29 09:14:40,266: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:14:40,266: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:14:40,266: ERROR: 
2025-07-29 09:14:40,267: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:14:40,267: ERROR:     raise AssertionError(
2025-07-29 09:14:40,267: ERROR: ***************************************************
2025-07-29 09:14:40,268: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:14:40,268: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:14:40,268: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:14:40,268: ERROR: ***************************************************
2025-07-29 09:24:14,118: ERROR: Error running WSGI application
2025-07-29 09:24:14,120: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:14,120: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:14,120: ERROR:     from app import app as application
2025-07-29 09:24:14,121: ERROR: 
2025-07-29 09:24:14,121: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:14,121: ERROR:     def feed_back():
2025-07-29 09:24:14,121: ERROR: 
2025-07-29 09:24:14,121: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:14,121: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:14,121: ERROR: 
2025-07-29 09:24:14,122: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:14,122: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:14,122: ERROR: 
2025-07-29 09:24:14,122: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:14,122: ERROR:     raise AssertionError(
2025-07-29 09:24:14,122: ERROR: ***************************************************
2025-07-29 09:24:14,122: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:14,123: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:14,123: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:14,123: ERROR: ***************************************************
2025-07-29 09:24:17,907: ERROR: Error running WSGI application
2025-07-29 09:24:17,907: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:17,908: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:17,908: ERROR:     from app import app as application
2025-07-29 09:24:17,908: ERROR: 
2025-07-29 09:24:17,908: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:17,908: ERROR:     def feed_back():
2025-07-29 09:24:17,909: ERROR: 
2025-07-29 09:24:17,909: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:17,909: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:17,909: ERROR: 
2025-07-29 09:24:17,909: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:17,909: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:17,909: ERROR: 
2025-07-29 09:24:17,910: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:17,910: ERROR:     raise AssertionError(
2025-07-29 09:24:17,910: ERROR: ***************************************************
2025-07-29 09:24:17,910: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:17,910: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:17,910: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:17,910: ERROR: ***************************************************
2025-07-29 09:24:18,342: ERROR: Error running WSGI application
2025-07-29 09:24:18,343: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:18,343: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:18,343: ERROR:     from app import app as application
2025-07-29 09:24:18,343: ERROR: 
2025-07-29 09:24:18,344: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:18,344: ERROR:     def feed_back():
2025-07-29 09:24:18,344: ERROR: 
2025-07-29 09:24:18,344: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:18,344: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:18,344: ERROR: 
2025-07-29 09:24:18,345: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:18,345: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:18,345: ERROR: 
2025-07-29 09:24:18,345: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:18,345: ERROR:     raise AssertionError(
2025-07-29 09:24:18,345: ERROR: ***************************************************
2025-07-29 09:24:18,345: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:18,347: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:18,347: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:18,347: ERROR: ***************************************************
2025-07-29 09:24:18,361: ERROR: Error running WSGI application
2025-07-29 09:24:18,362: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:18,362: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:18,362: ERROR:     from app import app as application
2025-07-29 09:24:18,363: ERROR: 
2025-07-29 09:24:18,363: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:18,363: ERROR:     def feed_back():
2025-07-29 09:24:18,363: ERROR: 
2025-07-29 09:24:18,363: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:18,364: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:18,364: ERROR: 
2025-07-29 09:24:18,364: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:18,364: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:18,364: ERROR: 
2025-07-29 09:24:18,364: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:18,365: ERROR:     raise AssertionError(
2025-07-29 09:24:18,365: ERROR: ***************************************************
2025-07-29 09:24:18,365: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:18,365: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:18,365: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:18,365: ERROR: ***************************************************
2025-07-29 09:24:24,266: ERROR: Error running WSGI application
2025-07-29 09:24:24,267: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:24,267: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:24,267: ERROR:     from app import app as application
2025-07-29 09:24:24,267: ERROR: 
2025-07-29 09:24:24,267: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:24,268: ERROR:     def feed_back():
2025-07-29 09:24:24,268: ERROR: 
2025-07-29 09:24:24,268: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:24,268: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:24,268: ERROR: 
2025-07-29 09:24:24,268: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:24,268: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:24,269: ERROR: 
2025-07-29 09:24:24,269: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:24,269: ERROR:     raise AssertionError(
2025-07-29 09:24:24,269: ERROR: ***************************************************
2025-07-29 09:24:24,269: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:24,269: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:24,269: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:24,269: ERROR: ***************************************************
2025-07-29 09:24:24,274: ERROR: Error running WSGI application
2025-07-29 09:24:24,275: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:24,275: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:24,275: ERROR:     from app import app as application
2025-07-29 09:24:24,275: ERROR: Error running WSGI application
2025-07-29 09:24:24,275: ERROR: 
2025-07-29 09:24:24,275: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:24,276: ERROR:     def feed_back():
2025-07-29 09:24:24,276: ERROR: 
2025-07-29 09:24:24,276: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:24:24,276: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:24,276: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:24:24,276: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:24,276: ERROR: 
2025-07-29 09:24:24,276: ERROR:     from app import app as application
2025-07-29 09:24:24,276: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:24,277: ERROR: 
2025-07-29 09:24:24,277: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:24,277: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:24:24,277: ERROR: 
2025-07-29 09:24:24,277: ERROR:     def feed_back():
2025-07-29 09:24:24,277: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:24,277: ERROR: 
2025-07-29 09:24:24,277: ERROR:     raise AssertionError(
2025-07-29 09:24:24,277: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:24:24,277: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:24:24,277: ERROR: ***************************************************
2025-07-29 09:24:24,277: ERROR: 
2025-07-29 09:24:24,277: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:24,277: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:24:24,277: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:24,278: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:24:24,278: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:24,278: ERROR: 
2025-07-29 09:24:24,278: ERROR: ***************************************************
2025-07-29 09:24:24,278: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:24:24,278: ERROR:     raise AssertionError(
2025-07-29 09:24:24,278: ERROR: ***************************************************
2025-07-29 09:24:24,278: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:24:24,279: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:24:24,279: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:24:24,279: ERROR: ***************************************************
2025-07-29 09:41:59,234: ERROR: Error running WSGI application
2025-07-29 09:41:59,239: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:41:59,239: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:41:59,239: ERROR:     from app import app as application
2025-07-29 09:41:59,239: ERROR: 
2025-07-29 09:41:59,240: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:41:59,240: ERROR:     def feed_back():
2025-07-29 09:41:59,240: ERROR: 
2025-07-29 09:41:59,240: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:41:59,240: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:41:59,240: ERROR: 
2025-07-29 09:41:59,241: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:41:59,241: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:41:59,241: ERROR: 
2025-07-29 09:41:59,241: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:41:59,241: ERROR:     raise AssertionError(
2025-07-29 09:41:59,242: ERROR: ***************************************************
2025-07-29 09:41:59,242: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:41:59,242: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:41:59,242: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:41:59,243: ERROR: ***************************************************
2025-07-29 09:42:00,566: ERROR: Error running WSGI application
2025-07-29 09:42:00,571: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:42:00,571: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:42:00,571: ERROR:     from app import app as application
2025-07-29 09:42:00,571: ERROR: 
2025-07-29 09:42:00,571: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:42:00,572: ERROR:     def feed_back():
2025-07-29 09:42:00,572: ERROR: 
2025-07-29 09:42:00,572: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:42:00,572: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:42:00,572: ERROR: 
2025-07-29 09:42:00,572: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:42:00,573: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:42:00,573: ERROR: 
2025-07-29 09:42:00,573: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:42:00,573: ERROR:     raise AssertionError(
2025-07-29 09:42:00,573: ERROR: ***************************************************
2025-07-29 09:42:00,573: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:42:00,573: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:42:00,574: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:42:00,574: ERROR: ***************************************************
2025-07-29 09:43:40,778: ERROR: Error running WSGI application
2025-07-29 09:43:40,782: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:43:40,782: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:43:40,782: ERROR:     from app import app as application
2025-07-29 09:43:40,782: ERROR: 
2025-07-29 09:43:40,782: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:43:40,782: ERROR:     def test():
2025-07-29 09:43:40,783: ERROR: 
2025-07-29 09:43:40,783: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:43:40,783: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:43:40,783: ERROR: 
2025-07-29 09:43:40,783: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:43:40,783: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:43:40,783: ERROR: 
2025-07-29 09:43:40,784: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:43:40,784: ERROR:     raise AssertionError(
2025-07-29 09:43:40,784: ERROR: ***************************************************
2025-07-29 09:43:40,784: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:43:40,784: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:43:40,784: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:43:40,785: ERROR: ***************************************************
2025-07-29 09:43:43,726: ERROR: Error running WSGI application
2025-07-29 09:43:43,728: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: feed_back
2025-07-29 09:43:43,728: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 09:43:43,728: ERROR:     from app import app as application
2025-07-29 09:43:43,728: ERROR: 
2025-07-29 09:43:43,729: ERROR:   File "/home/ocottrell/unemployment/app.py", line 144, in <module>
2025-07-29 09:43:43,729: ERROR:     def test():
2025-07-29 09:43:43,729: ERROR: 
2025-07-29 09:43:43,729: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 09:43:43,729: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 09:43:43,729: ERROR: 
2025-07-29 09:43:43,729: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 09:43:43,730: ERROR:     return f(self, *args, **kwargs)
2025-07-29 09:43:43,730: ERROR: 
2025-07-29 09:43:43,730: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 09:43:43,730: ERROR:     raise AssertionError(
2025-07-29 09:43:43,730: ERROR: ***************************************************
2025-07-29 09:43:43,730: ERROR: If you're seeing an import error and don't know why,
2025-07-29 09:43:43,730: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 09:43:43,731: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 09:43:43,731: ERROR: ***************************************************
2025-07-29 09:43:56,118: ERROR: Exception on /test [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 145, in test
    return render_template('test.py')
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ocottrell/unemployment/templates/test.py", line 106, in template
    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; margin: 20px; color: #333; }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
2025-07-29 13:23:32,883: INFO: Email sent successfully to farooque.reactjs@gmail.com
2025-07-29 17:59:45,376: ERROR: Error running WSGI application
2025-07-29 17:59:45,386: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: send_resume_email
2025-07-29 17:59:45,386: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 17:59:45,386: ERROR:     from app import app as application
2025-07-29 17:59:45,387: ERROR: 
2025-07-29 17:59:45,387: ERROR:   File "/home/ocottrell/unemployment/app.py", line 612, in <module>
2025-07-29 17:59:45,387: ERROR:     def send_resume_email():
2025-07-29 17:59:45,388: ERROR: 
2025-07-29 17:59:45,388: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 17:59:45,388: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 17:59:45,389: ERROR: 
2025-07-29 17:59:45,389: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 17:59:45,389: ERROR:     return f(self, *args, **kwargs)
2025-07-29 17:59:45,389: ERROR: 
2025-07-29 17:59:45,389: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 17:59:45,390: ERROR:     raise AssertionError(
2025-07-29 17:59:45,390: ERROR: ***************************************************
2025-07-29 17:59:45,390: ERROR: If you're seeing an import error and don't know why,
2025-07-29 17:59:45,390: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 17:59:45,390: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 17:59:45,391: ERROR: ***************************************************
2025-07-29 17:59:59,527: ERROR: Error running WSGI application
2025-07-29 17:59:59,532: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: send_resume_email
2025-07-29 17:59:59,532: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 17:59:59,533: ERROR:     from app import app as application
2025-07-29 17:59:59,533: ERROR: 
2025-07-29 17:59:59,533: ERROR:   File "/home/ocottrell/unemployment/app.py", line 612, in <module>
2025-07-29 17:59:59,533: ERROR:     def send_resume_email():
2025-07-29 17:59:59,533: ERROR: 
2025-07-29 17:59:59,534: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 17:59:59,534: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 17:59:59,534: ERROR: 
2025-07-29 17:59:59,534: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 17:59:59,534: ERROR:     return f(self, *args, **kwargs)
2025-07-29 17:59:59,535: ERROR: 
2025-07-29 17:59:59,535: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 17:59:59,535: ERROR:     raise AssertionError(
2025-07-29 17:59:59,535: ERROR: ***************************************************
2025-07-29 17:59:59,536: ERROR: If you're seeing an import error and don't know why,
2025-07-29 17:59:59,536: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 17:59:59,536: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 17:59:59,536: ERROR: ***************************************************
2025-07-29 18:00:03,917: ERROR: Error running WSGI application
2025-07-29 18:00:03,918: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: send_resume_email
2025-07-29 18:00:03,918: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:00:03,918: ERROR:     from app import app as application
2025-07-29 18:00:03,918: ERROR: 
2025-07-29 18:00:03,918: ERROR:   File "/home/ocottrell/unemployment/app.py", line 612, in <module>
2025-07-29 18:00:03,919: ERROR:     def send_resume_email():
2025-07-29 18:00:03,919: ERROR: 
2025-07-29 18:00:03,919: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 18:00:03,919: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 18:00:03,919: ERROR: 
2025-07-29 18:00:03,919: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 18:00:03,920: ERROR:     return f(self, *args, **kwargs)
2025-07-29 18:00:03,920: ERROR: 
2025-07-29 18:00:03,920: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 18:00:03,921: ERROR:     raise AssertionError(
2025-07-29 18:00:03,922: ERROR: ***************************************************
2025-07-29 18:00:03,927: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:00:03,927: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:00:03,927: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:00:03,927: ERROR: ***************************************************
2025-07-29 18:00:28,078: ERROR: Error running WSGI application
2025-07-29 18:00:28,083: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: send_resume_email
2025-07-29 18:00:28,084: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:00:28,084: ERROR:     from app import app as application
2025-07-29 18:00:28,084: ERROR: 
2025-07-29 18:00:28,084: ERROR:   File "/home/ocottrell/unemployment/app.py", line 612, in <module>
2025-07-29 18:00:28,085: ERROR:     def send_resume_email():
2025-07-29 18:00:28,085: ERROR: 
2025-07-29 18:00:28,085: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 18:00:28,085: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 18:00:28,086: ERROR: 
2025-07-29 18:00:28,086: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 18:00:28,087: ERROR:     return f(self, *args, **kwargs)
2025-07-29 18:00:28,087: ERROR: 
2025-07-29 18:00:28,087: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 18:00:28,087: ERROR:     raise AssertionError(
2025-07-29 18:00:28,088: ERROR: ***************************************************
2025-07-29 18:00:28,088: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:00:28,088: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:00:28,088: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:00:28,088: ERROR: ***************************************************
2025-07-29 18:00:32,911: ERROR: Error running WSGI application
2025-07-29 18:00:32,912: ERROR: AssertionError: View function mapping is overwriting an existing endpoint function: send_resume_email
2025-07-29 18:00:32,912: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:00:32,912: ERROR:     from app import app as application
2025-07-29 18:00:32,912: ERROR: 
2025-07-29 18:00:32,913: ERROR:   File "/home/ocottrell/unemployment/app.py", line 612, in <module>
2025-07-29 18:00:32,913: ERROR:     def send_resume_email():
2025-07-29 18:00:32,913: ERROR: 
2025-07-29 18:00:32,913: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 440, in decorator
2025-07-29 18:00:32,913: ERROR:     self.add_url_rule(rule, endpoint, f, **options)
2025-07-29 18:00:32,913: ERROR: 
2025-07-29 18:00:32,914: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 56, in wrapper_func
2025-07-29 18:00:32,914: ERROR:     return f(self, *args, **kwargs)
2025-07-29 18:00:32,914: ERROR: 
2025-07-29 18:00:32,914: ERROR:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
2025-07-29 18:00:32,915: ERROR:     raise AssertionError(
2025-07-29 18:00:32,915: ERROR: ***************************************************
2025-07-29 18:00:32,915: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:00:32,915: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:00:32,916: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:00:32,916: ERROR: ***************************************************
2025-07-29 18:02:48,216: ERROR: Exception on /send-resume-email [POST]
Traceback (most recent call last):
  File "/home/ocottrell/unemployment/app.py", line 358, in send_resume_email
    if not recipient_email or not re.match(email_regex, recipient_email):
NameError: name 're' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 416, in send_resume_email
    logging.error(f"Unexpected error for {recipient_email}: {str(e)}\n{traceback.format_exc()}")
NameError: name 'traceback' is not defined
2025-07-29 18:02:51,719: ERROR: Exception on /send-resume-email [POST]
Traceback (most recent call last):
  File "/home/ocottrell/unemployment/app.py", line 358, in send_resume_email
    if not recipient_email or not re.match(email_regex, recipient_email):
NameError: name 're' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ocottrell/unemployment/app.py", line 416, in send_resume_email
    logging.error(f"Unexpected error for {recipient_email}: {str(e)}\n{traceback.format_exc()}")
NameError: name 'traceback' is not defined
2025-07-29 18:04:02,778: ERROR: Unexpected error: name 'MIMEApplication' is not defined
2025-07-29 18:04:08,287: ERROR: Unexpected error: name 'MIMEApplication' is not defined
2025-07-29 18:15:34,144: ERROR: OSError: write error
2025-07-29 18:15:35,207: ERROR: OSError: write error
2025-07-29 18:15:36,320: ERROR: OSError: write error
2025-07-29 18:25:17,692: ERROR: Unexpected error: name 'SMTP_CONFIG' is not defined
2025-07-29 18:36:11,549: ERROR: Unexpected error: name 're' is not defined
2025-07-29 18:54:42,320: ERROR: Unexpected error: name 're' is not defined
2025-07-29 18:54:45,329: ERROR: Unexpected error: name 're' is not defined
2025-07-29 18:55:03,781: ERROR: Unexpected error: name 're' is not defined
2025-07-29 18:57:44,346: ERROR: Error running WSGI application
2025-07-29 18:57:44,351: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:57:44,351: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:57:44,351: ERROR:     from app import app as application
2025-07-29 18:57:44,351: ERROR: 
2025-07-29 18:57:44,352: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:57:44,352: ERROR:     if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:57:44,352: ERROR: ***************************************************
2025-07-29 18:57:44,352: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:57:44,353: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:57:44,353: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:57:44,353: ERROR: ***************************************************
2025-07-29 18:57:47,726: ERROR: Error running WSGI application
2025-07-29 18:57:47,727: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:57:47,727: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:57:47,728: ERROR:     from app import app as application
2025-07-29 18:57:47,728: ERROR: 
2025-07-29 18:57:47,728: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:57:47,728: ERROR:     if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:57:47,729: ERROR: ***************************************************
2025-07-29 18:57:47,729: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:57:47,729: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:57:47,729: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:57:47,730: ERROR: ***************************************************
2025-07-29 18:58:51,437: ERROR: Error running WSGI application
2025-07-29 18:58:51,472: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:58:51,473: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:58:51,473: ERROR:     from app import app as application
2025-07-29 18:58:51,473: ERROR: 
2025-07-29 18:58:51,473: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:58:51,473: ERROR:     # if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:58:51,474: ERROR: ***************************************************
2025-07-29 18:58:51,474: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:58:51,474: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:58:51,474: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:58:51,475: ERROR: ***************************************************
2025-07-29 18:58:54,563: ERROR: Error running WSGI application
2025-07-29 18:58:54,565: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:58:54,566: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:58:54,566: ERROR:     from app import app as application
2025-07-29 18:58:54,567: ERROR: 
2025-07-29 18:58:54,567: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:58:54,567: ERROR:     # if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:58:54,567: ERROR: ***************************************************
2025-07-29 18:58:54,568: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:58:54,568: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:58:54,568: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:58:54,568: ERROR: ***************************************************
2025-07-29 18:58:54,897: ERROR: Error running WSGI application
2025-07-29 18:58:54,898: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:58:54,898: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:58:54,898: ERROR:     from app import app as application
2025-07-29 18:58:54,898: ERROR: 
2025-07-29 18:58:54,899: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:58:54,899: ERROR:     # if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:58:54,899: ERROR: ***************************************************
2025-07-29 18:58:54,899: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:58:54,900: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:58:54,900: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:58:54,900: ERROR: ***************************************************
2025-07-29 18:58:55,126: ERROR: Error running WSGI application
2025-07-29 18:58:55,130: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:58:55,130: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:58:55,131: ERROR:     from app import app as application
2025-07-29 18:58:55,131: ERROR: 
2025-07-29 18:58:55,131: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:58:55,131: ERROR:     # if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:58:55,132: ERROR: ***************************************************
2025-07-29 18:58:55,132: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:58:55,132: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:58:55,132: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:58:55,132: ERROR: ***************************************************
2025-07-29 18:58:55,666: ERROR: Error running WSGI application
2025-07-29 18:58:55,667: ERROR: NameError: name 'SMTP_USER' is not defined
2025-07-29 18:58:55,667: ERROR:   File "/var/www/stdavid_stake-employment_com_wsgi.py", line 20, in <module>
2025-07-29 18:58:55,667: ERROR:     from app import app as application
2025-07-29 18:58:55,668: ERROR: 
2025-07-29 18:58:55,668: ERROR:   File "/home/ocottrell/unemployment/app.py", line 56, in <module>
2025-07-29 18:58:55,668: ERROR:     # if not SMTP_USER or not SMTP_PASSWORD:
2025-07-29 18:58:55,668: ERROR: ***************************************************
2025-07-29 18:58:55,668: ERROR: If you're seeing an import error and don't know why,
2025-07-29 18:58:55,668: ERROR: we have a dedicated help page to help you debug: 
2025-07-29 18:58:55,669: ERROR: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-07-29 18:58:55,669: ERROR: ***************************************************
2025-07-29 18:59:12,820: ERROR: Unexpected error: 'from_email'
2025-07-29 19:00:24,858: ERROR: Unexpected error: 'from_email'
2025-07-29 19:01:09,082: INFO: Email sent successfully to farooque.reactjs@gmail.com
2025-07-29 19:01:10,611: INFO: Email sent successfully to farooque.reactjs@gmail.com
2025-07-29 19:06:16,648: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-29 19:06:17,512: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-29 19:06:18,241: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-29 19:10:49,850: ERROR: Unexpected error: name 'SMTP_CONFIG' is not defined
2025-07-29 19:18:07,656: ERROR: OSError: write error
2025-07-29 19:18:14,869: ERROR: OSError: write error
2025-07-29 19:18:17,442: ERROR: OSError: write error
2025-07-29 19:18:31,334: ERROR: OSError: write error
2025-07-29 19:18:39,872: ERROR: OSError: write error
2025-07-29 19:18:49,967: ERROR: OSError: write error
2025-07-29 19:18:56,036: ERROR: OSError: write error
2025-07-29 19:18:59,868: ERROR: OSError: write error
2025-07-29 19:19:03,524: ERROR: OSError: write error
2025-07-29 19:19:06,479: ERROR: OSError: write error
2025-07-29 19:20:05,433: ERROR: OSError: write error
2025-07-29 19:30:54,236: INFO: Email sent successfully to farooque.reactjs@gmail.com
2025-07-29 19:38:46,660: ERROR: OSError: write error
2025-07-29 19:38:54,795: ERROR: OSError: write error
2025-07-29 19:40:02,262: ERROR: OSError: write error
2025-07-29 19:40:05,334: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-29 19:40:06,882: ERROR: OSError: write error
2025-07-29 19:40:10,450: ERROR: OSError: write error
2025-07-30 03:59:20,775: INFO: Email sent successfully to ocottrell@gmail.com
2025-07-30 09:36:43,917: ERROR: OSError: write error
2025-07-30 09:52:25,199: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-30 10:13:06,082: ERROR: No file attached
2025-07-30 10:19:53,195: INFO: Email sent successfully to akanjiabass75@gmail.com
2025-07-30 14:58:02,377: ERROR: OSError: write error
2025-07-30 14:58:03,930: ERROR: OSError: write error
2025-07-30 14:58:05,777: ERROR: OSError: write error
2025-07-30 14:58:06,809: ERROR: OSError: write error
2025-07-30 14:58:08,255: ERROR: OSError: write error
2025-07-30 14:58:09,794: ERROR: OSError: write error
2025-07-30 14:58:11,221: ERROR: OSError: write error
2025-07-30 14:58:12,255: ERROR: OSError: write error
